/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Medicine } from './types';

export const INITIAL_MEDICINES: Medicine[] = [
  { id: 1, name: 'DNS (محلول وريدي)', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 5 }, unit: 'كرتون', category: 'محاليل وريدية', status: 'ناقص' },
  { id: 2, name: 'R/L (محلول رينجر لاكتات)', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 5 }, unit: 'كرتون', category: 'محاليل وريدية', status: 'ناقص' },
  { id: 3, name: 'N/S (محلول ملحي)', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'كرتون', category: 'محاليل وريدية', status: 'متوفر' },
  { id: 4, name: 'Dextrose 5% 500ml', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'محاليل وريدية', status: 'متوفر' },
  { id: 5, name: 'Levofloxacin infusion', received: 7, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'مغذية', category: 'محاليل وريدية', status: 'متوفر' },
  { id: 6, name: 'Ciprofloxacin infusion', received: 10, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'مغذية', category: 'محاليل وريدية', status: 'متوفر' },
  { id: 7, name: 'Paracetamol infusion', received: 15, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'مغذية', category: 'محاليل وريدية', status: 'متوفر' },
  { id: 8, name: 'Vit C inj', received: 3, dispensedByPoint: { 'الرباط': 1, 'التواهي': 1 }, unit: 'باكت', category: 'فيتامينات', status: 'متوفر' },
  { id: 9, name: 'Vit B Complex inj', received: 3, dispensedByPoint: { 'الرباط': 1, 'التواهي': 0 }, unit: 'باكت', category: 'فيتامينات', status: 'متوفر' },
  { id: 10, name: 'Neurobion', received: 2, dispensedByPoint: { 'الرباط': 1, 'التواهي': 0 }, unit: 'باكت', category: 'فيتامينات', status: 'متوفر' },
  { id: 11, name: 'Ceftriaxone inj 1g', received: 30, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'فيال', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 12, name: 'Augmentin Tab 1g', received: 10, dispensedByPoint: { 'الرباط': 2, 'التواهي': 0 }, unit: 'باكت', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 13, name: 'Amoxil Cap', received: 7, dispensedByPoint: { 'الرباط': 2, 'التواهي': 0 }, unit: 'باكت', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 14, name: 'Meticillin Tab', received: 4, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 15, name: 'Flagyl Tab', received: 2, dispensedByPoint: { 'الرباط': 1, 'التواهي': 0 }, unit: 'باكت', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 16, name: 'Azithromycin Tab 500mg', received: 5, dispensedByPoint: { 'الرباط': 0, 'التواهي': 1 }, unit: 'باكت', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 17, name: 'Bactrim Tab', received: 10, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'شريط', category: 'مضادات حيوية', status: 'متوفر' },
  { id: 18, name: 'Diclofen inj 75mg', received: 4, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مسكنات', status: 'متوفر' },
  { id: 19, name: 'Diclofen Tab 50mg', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مسكنات', status: 'متوفر' },
  { id: 20, name: 'Panadol Tab', received: 10, dispensedByPoint: { 'الرباط': 0, 'التواهي': 2 }, unit: 'باكت', category: 'مسكنات', status: 'متوفر' },
  { id: 21, name: 'Solpadeine', received: 10, dispensedByPoint: { 'الرباط': 2, 'التواهي': 0 }, unit: 'باكت', category: 'مسكنات', status: 'متوفر' },
  { id: 22, name: 'Panadol Cold', received: 2, dispensedByPoint: { 'الرباط': 1, 'التواهي': 0 }, unit: 'باكت', category: 'مسكنات', status: 'متوفر' },
  { id: 23, name: 'Brufen Tab', received: 1, dispensedByPoint: { 'الرباط': 2, 'التواهي': 0 }, unit: 'باكت', category: 'مسكنات', status: 'ناقص' },
  { id: 24, name: 'Emistop inj', received: 5, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'جهاز هضمي', status: 'متوفر' },
  { id: 25, name: 'Pantoprazole inj 40mg', received: 10, dispensedByPoint: { 'الرباط': 5, 'التواهي': 2 }, unit: 'فيال', category: 'جهاز هضمي', status: 'متوفر' },
  { id: 26, name: 'Lomec Cap', received: 10, dispensedByPoint: { 'الرباط': 2, 'التواهي': 2 }, unit: 'باكت', category: 'جهاز هضمي', status: 'متوفر' },
  { id: 27, name: 'Omid Cap', received: 4, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'جهاز هضمي', status: 'متوفر' },
  { id: 28, name: 'Orisat', received: 5, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'جهاز هضمي', status: 'متوفر' },
  { id: 29, name: 'Magnesia inj', received: 3, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'أدوية عامة', status: 'متوفر' },
  { id: 30, name: 'Avil inj', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'أدوية عامة', status: 'متوفر' },
  { id: 31, name: 'Dexamethasone inj', received: 3, dispensedByPoint: { 'الرباط': 1, 'التواهي': 0 }, unit: 'باكت', category: 'أدوية عامة', status: 'متوفر' },
  { id: 32, name: 'Artemether inj', received: 15, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'أدوية عامة', status: 'متوفر' },
  { id: 33, name: 'Hydrocortisone inj 100mg', received: 5, dispensedByPoint: { 'الرباط': 3, 'التواهي': 0 }, unit: 'فيال', category: 'أدوية عامة', status: 'متوفر' },
  { id: 34, name: 'Hydrocortisone Cream', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'تيوب', category: 'أدوية عامة', status: 'متوفر' },
  { id: 35, name: 'Sterile Gauze', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 5 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'ناقص' },
  { id: 36, name: 'Bandage', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 37, name: 'Gloves', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 38, name: 'Lidocaine Vial 20ml', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'فيال', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 39, name: 'Iodine', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'لتر', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 40, name: 'Plaster Tabs', received: 5, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'شريط', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 41, name: 'Tetracycline Eye Oint', received: 5, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'تيوب', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 42, name: 'Nasal Drops', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'علبة', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 43, name: 'Castor Oil', received: 10, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'شريط', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 44, name: 'Syringe 10cc', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 45, name: 'Syringe 5cc', received: 2, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 46, name: 'Tetracycline Skin Oint', received: 3, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'تيوب', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 47, name: 'Cannula 22', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 48, name: 'Plaster 7.5cm', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'باكت', category: 'مستلزمات طبية', status: 'متوفر' },
  { id: 49, name: 'Pantol Spray', received: 1, dispensedByPoint: { 'الرباط': 0, 'التواهي': 0 }, unit: 'علبة', category: 'مستلزمات طبية', status: 'متوفر' },
];
